Forum Integrate sort button with backend api
Al-Andrew/SmartHouse-Builder pull request #175
Opened 2022-05-22 18:23 UTC by baranceanuvlad

fix #174 
Am facut sort api si integrare

2022-05-22 19:59 UTC, Al-Andrew requested changes
Regarding the uri change comments. Consider using a base-uri variable which you can append the routes on for ease of use. 
Also the sorting code seems like it's doing a lot more work on the frontend than it should.

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/screens/MyPosts.dart
> +      /*Post.getPosts().then(
should we commit this commented code?

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +            'http://localhost:8070/api/forum/comment/$postId',
This will break on hosted release. please use host uris

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +                'http://localhost:8070/api/forum/comment/$postId',
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +            await http.post(Uri.parse('http://localhost:8070/api/forum/sort/2'),
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +                'http://localhost:8070/api/forum/comment/$postId',
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +            await http.post(Uri.parse('http://localhost:8070/api/forum/sort/3'),
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +                'http://localhost:8070/api/forum/comment/$postId',
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +            await http.post(Uri.parse('http://localhost:8070/api/forum/sort/1'),
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +                'http://localhost:8070/api/forum/comment/$postId',
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +            await http.post(Uri.parse('http://localhost:8070/api/forum/sort/2'),
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +                'http://localhost:8070/api/forum/comment/$postId',
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +            await http.post(Uri.parse('http://localhost:8070/api/forum/sort/3'),
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +                'http://localhost:8070/api/forum/comment/$postId',
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +            await http.post(Uri.parse('http://localhost:8070/api/forum/sort/1'),
this will break on host. please use host uri

2022-05-22 19:59 UTC, Al-Andrew commented on FrontEnd/lib/forum/classes/PostClass.dart
> +    print(checkedCommented);
do we need these debug prints on host?

2022-05-22 20:29 UTC, baranceanuvlad commented
Eu zic ca aia cu uri poti sa il pui issue si sa il asignezi cuiva ca la forum problema exista peste tot si trebuie schimbat si sortul in frontend face numai 4 if-uri

2022-05-23 10:32 UTC, OpariucRares requested changes

2022-05-23 10:32 UTC, OpariucRares commented on FrontEnd/lib/forum/classes/PostClass.dart
> +          Uri.http('localhost:8070', '/api/forum/sort/', queryParameters);
local

2022-05-23 10:32 UTC, OpariucRares commented on FrontEnd/lib/forum/classes/PostClass.dart
> +          Uri.http('localhost:8070', '/api/forum/sort/', queryParameters);
local

2022-05-23 10:50 UTC, OpariucRares approved these changes
pare bine

2022-05-23 10:54 UTC, Al-Andrew approved these changes
pare ok. dar vad ca nu ati introdus variabila de base-url, hai sa speram ca nu mai tre sa schimbam host-u pana e gata proiectu

2022-05-23 10:57 UTC, Al-Andrew commented
am facut issue #176 in legatura cu schimbare in intregul codebase pentru forum

2022-05-23 11:06 UTC, merged