Connected marketplace to database
Al-Andrew/SmartHouse-Builder pull request #197
Opened 2022-05-25 22:41 UTC by atcalcan

FIX #196

2022-05-25 22:44 UTC, cristiancibotariu commented
Doesn't load everytime, but works fine after a few refreshes.

2022-05-25 22:45 UTC, cristiancibotariu approved these changes

2022-05-26 06:43 UTC, Al-Andrew requested changes

2022-05-26 06:43 UTC, Al-Andrew commented on FrontEnd/lib/forum/CreatePost.dart
> +import 'dart:html';
these files already exist on main. but have been moved. try a pull

2022-05-26 07:21 UTC, merged