Forum Navigation for search and sort
Al-Andrew/SmartHouse-Builder pull request #201
Opened 2022-05-26 01:40 UTC by LapteacruCristian

fix #189 

HTML render
![image](https://user-images.githubusercontent.com/75312122/170397604-f7ee1831-3a02-4721-a358-28fded1bb4d8.png)

2022-05-26 06:10 UTC, OpariucRares requested changes
delete .idea and webscraper.iml

2022-05-26 06:14 UTC, OpariucRares approved these changes
pare bine

2022-05-26 06:17 UTC, cristiancibotariu approved these changes

2022-05-29 12:31 UTC, OpariucRares requested changes
small bug

2022-05-29 12:54 UTC, OpariucRares approved these changes

2022-05-29 12:55 UTC, merged